export enum LogTypes {
  BAD_REQUEST = 'BAD_REQUEST',
  SUCCESS = 'SUCCESS',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}

export enum LogReferenceTypes {
  USER = 'USER',
  AUTH = 'AUTH',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  ROLE = 'ROLE',
  TASK = 'TASK',
}
